# Generated by Django 5.1 on 2024-08-20 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('answer', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentArea',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_level_name', models.CharField(max_length=100)),
                ('sydney_participant', models.IntegerField(default=0)),
                ('sydney_percentile', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('sydney_average_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('student_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('student_total_assessed', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('student_area_assessed_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_area_assessed_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('participant', models.CharField(default='', max_length=100)),
                ('correct_answer_percentage_per_class', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('average_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('school_percentile', models.IntegerField(default=0)),
                ('correct_answer', models.CharField(default='', max_length=3)),
                ('category_id', models.CharField(default='0', max_length=50)),
                ('correct_answer_id', models.CharField(default='0', max_length=50)),
                ('assessment_area_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_app.assessmentarea')),
                ('award_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_app.award')),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_app.class')),
                ('school_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_app.school')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_app.student')),
                ('subject_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_app.subject')),
            ],
        ),
    ]
