# Generated by Django 5.1 on 2024-08-20 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summary',
            name='assessment_area_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='summary',
            name='award_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='summary',
            name='class_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='summary',
            name='school_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='summary',
            name='student_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='summary',
            name='subject_id',
            field=models.CharField(max_length=100),
        ),
    ]
