# Generated by Django 5.1 on 2024-08-20 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0002_alter_summary_assessment_area_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summary',
            name='average_score',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='summary',
            name='category_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='summary',
            name='correct_answer',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='summary',
            name='correct_answer_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='summary',
            name='correct_answer_percentage_per_class',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='summary',
            name='participant',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='summary',
            name='school_percentile',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='summary',
            name='student_area_assessed_score',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='summary',
            name='student_score',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='summary',
            name='student_total_assessed',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='summary',
            name='sydney_average_score',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='summary',
            name='sydney_participant',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='summary',
            name='sydney_percentile',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='summary',
            name='total_area_assessed_score',
            field=models.CharField(max_length=100),
        ),
    ]
